apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume-pod
spec:
  containers:
  - image: luksa/fortune
    name: html-generator
    volumeMounts:
    - name: html  # Volume name
      mountPath: /var/htdocs # Mount Directory in the container
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html # Volume name
      mountPath: /usr/share/nginx/html # Mount Directory in the container
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}