apiVersion: v1
kind: Pod
metadata:
  name: apache
spec:
  volumes:
    - name: app-pv-storage
      persistentVolumeClaim:
        claimName: app-volume-claim
  containers:
    - name: apache
      image: httpd
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/var/www/html"
          name: app-pv-storage