apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc # Replication Controller
spec:
  replicas: 3    # Number of pods
  selector:      # Label Selector (Look after the pods that have the following labels)
    app: frontend
  template:      # Pod template
    metadata:
      name: nginx
      labels:     # Pod label
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80